Fixes #26. Quote cssDir argument to allow spaces
Bug was causing the following error message:
    Error: Command failed: Individual stylesheets must be in the sass directory.